language: node_js
dist: trusty
sudo: false
node_js: 6

services:
  - docker

addons:
  apt:
     sources:
        - google-chrome
#     packages:
#        - dbus
#        - dbus-x11
#        - xvfb
#        - google-chrome-stable
#        - libnotify-cil-dev

env:
  global:
    - DISPLAY=":99.0"
    - KEY_FROM_LAYER=true
    - DO_NOT_SET_WSKPROPS=true
    - WINDOW_WIDTH=1400
    - WINDOW_HEIGHT=1050
    - NO_DEBUGGER_BREAKPOINTS=true
    - NO_NOTIFICATIONS=true
    - NO_FIRST_TIMER=true
    - UV_THREADPOOL_SIZE=64

install:
    - echo "API_HOST=foo" > ~/.wskprops
    - echo "AUTH=bar" >>  ~/.wskprops
    - (cd dist && npm install; cd ../app && npm install) &
    - (cd tests && npm install) &
    - (./tools/travis/setup.sh; ./tools/travis/build.sh; ./tools/travis/init_auth.sh) &
    - wait

script: echo "Running Tests!"

jobs:
  include:
     - stage: test
       script:
         - Xvfb :99 -screen 0 1400x1050x24 > /dev/null 2>&1 &
         - sudo apt-get install -y dbus dbus-x11 xvfb google-chrome-stable libnotify-cil-dev
         - (cd tests && npm run test)
       env: LAYER=01
     - script:
         - Xvfb :99 -screen 0 1400x1050x24 > /dev/null 2>&1 &
         - sudo apt-get install -y dbus dbus-x11 xvfb google-chrome-stable libnotify-cil-dev
         - (cd tests && npm run test)
       env: LAYER=02
     - script:
         - Xvfb :99 -screen 0 1400x1050x24 > /dev/null 2>&1 &
         - sudo apt-get install -y dbus dbus-x11 xvfb google-chrome-stable libnotify-cil-dev
         - (cd tests && npm run test)
       env: LAYER=03
     - script:
         - Xvfb :99 -screen 0 1400x1050x24 > /dev/null 2>&1 &
         - sudo apt-get install -y dbus dbus-x11 xvfb google-chrome-stable libnotify-cil-dev
         - (cd tests && npm run test)
       env: LAYER=04
     - script:
         - Xvfb :99 -screen 0 1400x1050x24 > /dev/null 2>&1 &
         - sudo apt-get install -y dbus dbus-x11 xvfb google-chrome-stable libnotify-cil-dev
         - (cd tests && npm run test)
       env: LAYER=05
     - script:
         - Xvfb :99 -screen 0 1400x1050x24 > /dev/null 2>&1 &
         - sudo apt-get install -y dbus dbus-x11 xvfb google-chrome-stable libnotify-cil-dev
         - (cd tests && npm run test)
       env: LAYER=06
     - script:
         - Xvfb :99 -screen 0 1400x1050x24 > /dev/null 2>&1 &
         - sudo apt-get install -y dbus dbus-x11 xvfb google-chrome-stable libnotify-cil-dev
         - (cd tests && npm run test)
       env: LAYER=07
     - script:
         - Xvfb :99 -screen 0 1400x1050x24 > /dev/null 2>&1 &
         - sudo apt-get install -y dbus dbus-x11 xvfb google-chrome-stable libnotify-cil-dev
         - (cd tests && npm run test)
       env: LAYER=08
