# the shell is a nodejs app
language: node_js
node_js: 8

dist: trusty

# docker, for openwhisk
sudo: required
services:
  - docker

#addons:
#  apt:
#     sources:
#        - google-chrome
#     packages:
#        - dbus
#        - dbus-x11
#        - xvfb
#        - google-chrome-stable
#        - libnotify-cil-dev

env:
  global:
    - DISPLAY=":99.0"
    - KEY_FROM_LAYER=true
    - DO_NOT_SET_WSKPROPS=true
    - REDIS_URL=redis://172.17.0.1:6379   # we'll pick up openwhisk's redis
    - WINDOW_WIDTH=1400
    - WINDOW_HEIGHT=1050
    - NO_DEBUGGER_BREAKPOINTS=true
    - NO_NOTIFICATIONS=true
    - NO_FIRST_TIMER=true
    - UV_THREADPOOL_SIZE=64

install:
    - echo "API_HOST=foo" > ~/.wskprops                                                  # dist/compile.sh needs something here
    - echo "AUTH=bar" >>  ~/.wskprops                                                    # ibid
    - (cd app && npm install) &                                                          # app npm install
    - (cd tests && npm install) &                                                        # tests npm install
    - (./tools/travis/setup.sh; ./tools/travis/build.sh; ./tools/travis/init_auth.sh) &  # initialize openwhisk and test docker
    - wait
    - cp tools/travis/Dockerfile .
    - docker build -t shell-test .                                                       # initialize test docker image

script: (cd tests && npm run test)

