language: node_js
node_js: 8
dist: trusty

services:
  - docker

addons:
  apt:
    packages:
      - bash

env:
  global:
    - REDIS_URL=redis://172.17.0.1:6379   # we'll pick up openwhisk's redis

install:
    - echo "API_HOST=foo" > ~/.wskprops                                                  # dist/compile.sh needs something here
    - echo "AUTH=bar" >>  ~/.wskprops                                                    # ibid
    - (cd app && npm install) &                                                          # app npm install
    - (cd tests && npm install) &                                                        # tests npm install
    - (./tools/travis/setup.sh; ./tools/travis/build.sh; ./tools/travis/init_auth.sh) &  # initialize openwhisk and test docker
    - wait
    - rm .dockerignore
    - cp tools/travis/Dockerfile .
    - docker build -t shell-test .                                                       # initialize test docker image

script: (cd tests && npm run test)

