language: node_js
dist: trusty
sudo: false
node_js: 6

services:
  - docker

addons:
  apt:
     sources:
        - google-chrome
     packages:
        - dbus
        - dbus-x11
        - xvfb
        - google-chrome-stable
        - libnotify-cil-dev

env:
  global:
    - DISPLAY=":99.0"
    - KEY_FROM_LAYER=true
    - DO_NOT_SET_WSKPROPS=true
    - REDIS_URL=redis://192.168.99.100:6379   # we'll pick up openwhisk's redis
    - WINDOW_WIDTH=1400
    - WINDOW_HEIGHT=1050
    - NO_DEBUGGER_BREAKPOINTS=true
    - NO_NOTIFICATIONS=true
    - NO_FIRST_TIMER=true
    - UV_THREADPOOL_SIZE=64

install:
    - echo "API_HOST=foo" > ~/.wskprops
    - echo "AUTH=bar" >>  ~/.wskprops
    - (cd dist && npm install; cd ../app && npm install) &
    - (cd tests && npm install) &
    - (./tools/travis/setup.sh; ./tools/travis/build.sh; ./tools/travis/init_auth.sh) &
    - Xvfb :99 -screen 0 1400x1050x24 > /dev/null 2>&1 &
    - wait

script: (cd tests && ./bin/runLocal.sh)

